-- =============================================================================
-- MySQL 8.0+ Schema — Product Catalog / Kaise PIM
-- UUIDs are generated by the application (uuid npm package), not the DB.
-- All tables use InnoDB + utf8mb4 for full Unicode and FK support.
-- =============================================================================

SET FOREIGN_KEY_CHECKS = 0;
SET NAMES utf8mb4;

-- ProductType
CREATE TABLE IF NOT EXISTS product_types (
    id          CHAR(36)     NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_product_types_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Global attribute definitions
CREATE TABLE IF NOT EXISTS attributes (
    id            CHAR(36)     NOT NULL,
    name          VARCHAR(255) NOT NULL,
    label         VARCHAR(255) NOT NULL,
    data_type     VARCHAR(50)  NOT NULL,
    unit          VARCHAR(50),
    is_filterable TINYINT(1)   NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_attributes_name (name),
    CONSTRAINT chk_attr_data_type CHECK (data_type IN ('string','number','boolean','date'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Attribute → ProductType mapping
CREATE TABLE IF NOT EXISTS product_type_attributes (
    id              CHAR(36)   NOT NULL,
    product_type_id CHAR(36)   NOT NULL,
    attribute_id    CHAR(36)   NOT NULL,
    is_required     TINYINT(1) NOT NULL DEFAULT 0,
    `order`         INT        NOT NULL DEFAULT 0,
    created_at      TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_pta (product_type_id, attribute_id),
    KEY idx_pta_product_type_id (product_type_id),
    KEY idx_pta_attribute_id    (attribute_id),
    CONSTRAINT fk_pta_product_type FOREIGN KEY (product_type_id) REFERENCES product_types(id) ON DELETE CASCADE,
    CONSTRAINT fk_pta_attribute   FOREIGN KEY (attribute_id)    REFERENCES attributes(id)    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Hierarchical categories with battery metadata
CREATE TABLE IF NOT EXISTS categories (
    id                CHAR(36)     NOT NULL,
    name              VARCHAR(255) NOT NULL,
    slug              VARCHAR(255) NOT NULL,
    parent_id         CHAR(36),
    description       TEXT,
    technology        VARCHAR(100),
    plate_type        VARCHAR(100),
    design_life_years VARCHAR(50),
    cycles            VARCHAR(100),
    capacity_range    VARCHAR(100),
    applications      TEXT,
    eurobat           TINYINT(1)   NOT NULL DEFAULT 0,
    characteristics   TEXT,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_categories_slug (slug),
    KEY idx_categories_parent_id  (parent_id),
    KEY idx_categories_technology (technology),
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Products
CREATE TABLE IF NOT EXISTS products (
    id              CHAR(36)     NOT NULL,
    name            VARCHAR(255) NOT NULL,
    slug            VARCHAR(255) NOT NULL,
    description     TEXT,
    product_type_id CHAR(36)     NOT NULL,
    status          VARCHAR(50)  NOT NULL DEFAULT 'draft',
    main_image_id   CHAR(36),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_products_slug (slug),
    KEY idx_products_product_type_id (product_type_id),
    KEY idx_products_status          (status),
    FULLTEXT KEY ft_products_search  (name, description),
    CONSTRAINT chk_product_status CHECK (status IN ('draft','published','archived')),
    CONSTRAINT fk_products_product_type FOREIGN KEY (product_type_id) REFERENCES product_types(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dynamic attribute values stored as JSON
CREATE TABLE IF NOT EXISTS product_attribute_values (
    id              CHAR(36)  NOT NULL,
    product_id      CHAR(36)  NOT NULL,
    attributes_json JSON      NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_pav_product_id (product_id),
    CONSTRAINT fk_pav_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Product ↔ Category (many-to-many)
CREATE TABLE IF NOT EXISTS product_categories (
    product_id  CHAR(36) NOT NULL,
    category_id CHAR(36) NOT NULL,
    PRIMARY KEY (product_id, category_id),
    KEY idx_product_categories_category_id (category_id),
    CONSTRAINT fk_pc_product  FOREIGN KEY (product_id)  REFERENCES products(id)   ON DELETE CASCADE,
    CONSTRAINT fk_pc_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Media files (images + PDFs)
CREATE TABLE IF NOT EXISTS media (
    id         CHAR(36)     NOT NULL,
    product_id CHAR(36)     NOT NULL,
    type       VARCHAR(50)  NOT NULL,
    url        TEXT         NOT NULL,
    title      VARCHAR(255),
    `order`    INT          NOT NULL DEFAULT 0,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_media_product_id (product_id),
    CONSTRAINT chk_media_type CHECK (type IN ('image','pdf')),
    CONSTRAINT fk_media_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Category feature bullets (applications, characteristics)
CREATE TABLE IF NOT EXISTS category_features (
    id          CHAR(36)     NOT NULL,
    category_id CHAR(36)     NOT NULL,
    type        VARCHAR(50)  NOT NULL,
    label       VARCHAR(255) NOT NULL,
    `order`     INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_category_features_category_id (category_id),
    KEY idx_category_features_type        (type),
    KEY idx_category_features_order       (category_id, type, `order`),
    CONSTRAINT fk_cf_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
